### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by itssource** [UnityGameAcademy/DOTSCompare#1]
As of 03/31/20 in Unity 2019.3.0f6 (with latest packages, updates installed)

Error on build:

Library\PackageCache\com.unity.collections@0.7.0-preview.2\Unity.Collections\CollectionHelper.cs(9,19): error CS0234: The type or namespace name 'CompilerServices' does not exist in the namespace 'Unity.Burst' (are you missing an assembly reference?)

**Comment by UnityGameAcademy** [comment]
This is using the Entities 0.5.1 package and HybridRenderer 0.3.3.  Going to guess there is a conflict with updating.  I am still able to open the repo project in Unity 2019.3.5f1.

**Comment by itssource** [comment]
Next I updated to the latest 2019.3.7f1 and see the following errors.

Library\PackageCache\com.unity.collections@0.7.0-Library\PackageCache\com.unity.collections@0.7.0-preview.2\Unity.Collections\CollectionHelper.cs(9,19): error CS0234: The type or namespace name 'CompilerServices' does not exist in the namespace 'Unity.Burst' (are you missing an assembly reference?)

Library\PackageCache\com.unity.collections@0.7.0-preview.2\Unity.Collections\NativeList.cs(8,19): error CS0234: The type or namespace name 'CompilerServices' does not exist in the namespace 'Unity.Burst' (are you missing an assembly reference?)

Library\PackageCache\com.unity.collections@0.7.0-preview.2\Unity.Collections\CollectionHelper.cs(172,18): error CS0246: The type or namespace name 'AssumeRangeAttribute' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.unity.collections@0.7.0-preview.2\Unity.Collections\CollectionHelper.cs(172,18): error CS0246: The type or namespace name 'AssumeRange' could not be found (are you missing a using directive or an assembly reference?)


Thanks for the quick reply before. Any timeline on when this project could be updated to this build or later of Unity 2019?

**Comment by UnityGameAcademy** [comment]
I opened the project with Unity 2019.3.0f6, with Entities 0.8.0 and HybridRenderer 0.4.0.

I was able to Play and also make a successful standalone build.

**Comment by itssource** [comment]
Interesting..

Here's my package versions. 

{
  "dependencies": {
    "com.unity.burst": "1.2.3",
    "com.unity.collab-proxy": "1.2.16",
    "com.unity.collections": "0.7.0-preview.2",
    "com.unity.entities": "0.8.0-preview.8",
    "com.unity.ide.rider": "1.1.4",
    "com.unity.ide.vscode": "1.1.4",
    "com.unity.platforms": "0.2.2-preview.9",
    "com.unity.rendering.hybrid": "0.4.0-preview.8",
    "com.unity.scriptablebuildpipeline": "1.6.5-preview",
    "com.unity.test-framework": "1.1.13",
    "com.unity.test-framework.performance": "2.0.9-preview",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.timeline": "1.2.14",
    "com.unity.ugui": "1.0.0",
    "nuget.mono-cecil": "0.1.6-preview",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

**Comment by UnityGameAcademy** [comment]
Are you trying to build for Android? I have only tested this on PC/Mac...

**Comment by itssource** [comment]
No, building on a Windows 10 Pro machine for the Windows platform (.exe).

**Comment by UnityGameAcademy** [comment]
I was able to open and play this on Unity 2019.3.6f1 
    "com.unity.entities": "0.8.0-preview.8"
    "com.unity.rendering.hybrid": "0.4.0-preview.8"

No conflicts and builds okay.  This is on my Mac laptop though.  Can check on my PC later today.

**Comment by itssource** [comment]
Yes, that would be great. I'm not sure what else to try.

**Comment by UnityGameAcademy** [comment]
I tried in on my Window 10 PC (home, not Pro)  running Unity 2019.3.6f1. It does crash occasionally but otherwise, it seems to run correctly.  As far as I can tell, everything is okay.  Really not sure what is causing the conflict in yours.

Here's the packages:
{
  "dependencies": {
    "com.unity.entities": "0.8.0-preview.8",
    "com.unity.ide.vscode": "1.1.4",
    "com.unity.rendering.hybrid": "0.4.0-preview.8",
    "com.unity.textmeshpro": "2.0.1",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0"
  }
}

**Comment by UnityGameAcademy** [comment]
Also, not sure where you are getting those extra dependencies:
"com.unity.burst": "1.2.3",
"com.unity.collab-proxy": "1.2.16",
"com.unity.collections": "0.7.0-preview.2",

**Comment by itssource** [comment]
Do you think that would be the cause though?

**Comment by UnityGameAcademy** [comment]
Sure looks like it.  Since they are related to the error messages.

**Comment by UnityGameAcademy** [comment]
Did you try opening a clean ZIP of the project from the repo?

**Comment by itssource** [comment]
I just tried it for the first time today, fresh download.

**Comment by UnityGameAcademy** [comment]
Yeah it feels like the dependencies are the issue.  Something is importing a package that is in conflict with the Entities package I am guessing.  I don't think it's the project itself that is causing it.  Did you try to download the ZIP and open it with the same version of Unity?

**Comment by itssource** [comment]
I'll try it again. Did you try in the latest 2019 on windows?

**Comment by UnityGameAcademy** [comment]
Yes, per my comment:
"I tried in on my Window 10 PC (home, not Pro) running Unity 2019.3.6f1"

I mean DOTS is not super stable yet.  It does crash once in a while.  But most of the time the project runs and builds just fine.

**Comment by itssource** [comment]
Okay, thanks.
