### ISSUE TITLE
GameManager's Mode of ECS Pure is not working (other two do)

### ISSUE THREAD

**Issue by itssource** [UnityGameAcademy/DOTSCompare#2]
I just did a fresh Clone of this project. And it works for me now. Thanks.

Something I ran into tonight, different.

Game Manager (inspector) Mode = ECS Pure (does not show any objects at Play Mode time. Do I need to do something else besides select the Mode = ECS Pure in the GameManager's Inspector dropdown field?

Otherwise, can you test this feature?  Classic and ECS Conversion work fine for me.

Thanks again.

**Comment by UnityGameAcademy** [comment]
Oh, I forgot when I updated Packages the other day.  ECS Pure requires a typeof RenderBounds to be added manually.  It doesn't do this for you automatically anymore.  I will republish the repo but you can fix this method in the Spawner script yourself until I can re-commit: 
`
        private void SetupECSPure()
        {
            if (mode == DemoMode.ECSPure)
            {
                defaultWorld = World.DefaultGameObjectInjectionWorld;
                entityManager = defaultWorld.EntityManager;
                archetype = entityManager.CreateArchetype
                (
                    typeof(Translation),
                    typeof(Rotation),
                    typeof(RenderMesh),
                    typeof(LocalToWorld),
                    typeof(MoveForward),
                    typeof(RenderBounds),
                    typeof(Scale)
                );
            }
        }
`

It's just one extra line that is now required for the latest Entities/HybridRenderer packages.

**Comment by itssource** [comment]
Thank you so much. And for the tutorials on DOTS. It's a great channel you have on YouTube.
(confirmed. this option works from my end as well now)
