### ISSUE TITLE
Getting Stopping Errors on Build with latest updates from repo

### ISSUE THREAD

**Issue by itssource** [UnityGameAcademy/DOTSCompare#3]
Can you try building and running this project now? I'm getting build errors. If it builds for you then I know it must be something here. Play mode works great though.

Thanks.

**Comment by UnityGameAcademy** [comment]
I have confirmed that the project builds on both Mac and PC using Unity 2019.3.6f1 ("com.unity.entities": "0.8.0-preview.8","com.unity.rendering.hybrid": "0.4.0-preview.8").  As DOTS is still under development, check the official release notes for incompatibility; there have been on and off again build issues with different machine configurations.
